adding tests from the test-a-thon
OHDSI/ParallelLogger pull request #12
Opened 2021-07-16 16:12 UTC by rossdwilliams

This is the sum of the work done by the Eurysteusian team to add more test coverage

2021-07-16 16:53 UTC, msuchard commented on tests/testthat/test-logging.R
> +
Maybe a few too many blank lines at EOF ... although it makes me smile because I hate having no blank lines at the end.

2021-07-16 16:53 UTC, msuchard approved these changes

2021-07-16 16:55 UTC, msuchard requested changes
R-check shows:  that `registerDefaultHandlers` is not exported.  You need to access it via 3-colons, i.e. ParallelLogger:::registerDefaultHandlers()

2021-07-19 11:33 UTC, rossdwilliams commented
fixed that ::: issue, also i removed stringr to reduce dependancies and cleaned up the empty lines

2021-07-19 11:39 UTC, schuemie approved these changes

2021-07-19 11:39 UTC, merged